## Import Data

In [40]:
import pandas as pd

In [41]:
data = pd.read_json("part-01.json")
data.head()

,review_id,reviewer,movie,rating,review_summary,review_date,spoiler_tag,review_detail,helpful
0,rw5704482,raeldor-96879,After Life (2019– ),9.0,Very Strong Season 2,3 May 2020,0,"I enjoyed the first season, but I must say I t...","[1, 1]"
1,rw5704483,dosleeb,The Valhalla Murders (2019– ),6.0,Icelandic detectives?,3 May 2020,0,I know Iceland is a small country and police d...,"[2, 2]"
2,rw5704484,brightconscious,Special OPS (2020– ),7.0,Nothing special,3 May 2020,0,"Except K K , no other actor looks comfortable ...","[0, 0]"
3,rw5704485,gasconyway,#BlackAF (2020– ),8.0,Good but,3 May 2020,0,I'm guessing that as a 62 year old white woman...,"[5, 9]"
4,rw5704487,mmason-15867,The Droving (2020),2.0,An honest review,3 May 2020,0,Here's the truth. There's not much to this mov...,"[26, 41]"

In [42]:
data.isna().sum()

review_id             0
reviewer              0
movie                 0
rating            51520
review_summary        0
review_date           0
spoiler_tag           0
review_detail         0
helpful               0
dtype: int64

## Drop Null Value Rating

In [43]:
data.dropna(subset=['rating'], inplace=True)
data = data.reset_index(drop=True)


ukuran_data = data.shape[0]
ukuran_data

958773

## Reduksi Dimensi

In [44]:
kolom_useless = ["reviewer","review_summary","review_date","spoiler_tag","helpful"]

for i in kolom_useless :
    del data[i]
    
data.head()

,review_id,movie,rating,review_detail
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t..."
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ..."
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...

## Sampling 20%

In [45]:
d_data = data.to_dict(orient="list")
d_data

{'review_id': ['rw5704482',
  'rw5704483',
  'rw5704484',
  'rw5704485',
  'rw5704487',
  'rw5704488',
  'rw5704489',
  'rw5704490',
  'rw5704491',
  'rw5704492',
  'rw5704494',
  'rw5704493',
  'rw5704497',
  'rw5704500',
  'rw5704499',
  'rw5704501',
  'rw5704502',
  'rw5704504',
  'rw5704503',
  'rw5704505',
  'rw5704507',
  'rw5704508',
  'rw5704509',
  'rw5704510',
  'rw5704511',
  'rw5704512',
  'rw5704513',
  'rw5704514',
  'rw5704515',
  'rw5704516',
  'rw5704517',
  'rw5704518',
  'rw5704519',
  'rw5704520',
  'rw5704521',
  'rw5704522',
  'rw5704523',
  'rw5704525',
  'rw5704526',
  'rw5704527',
  'rw5704528',
  'rw5704529',
  'rw5704530',
  'rw5704532',
  'rw5704531',
  'rw5704533',
  'rw5704535',
  'rw5704536',
  'rw5704537',
  'rw5704538',
  'rw5704539',
  'rw5704540',
  'rw5704541',
  'rw5704542',
  'rw5704543',
  'rw5704544',
  'rw5704545',
  'rw5704546',
  'rw5704548',
  'rw5704549',
  'rw5704550',
  'rw5704551',
  'rw5704552',
  'rw5704553',
  'rw5704555',
  'rw5704556',
  'rw5704557',
  'rw5704558',
  'rw5704559',
  'rw5704560',
  'rw5704561',
  'rw5704564',
  'rw5704565',
  'rw5704566',
  'rw5704567',
  'rw5704568',
  'rw5704569',
  'rw5704571',
  'rw5704572',
  'rw5704573',
  'rw5704574',
  'rw5704576',
  'rw5704575',
  'rw5704577',
  'rw5704578',
  'rw5704579',
  'rw5704580',
  'rw5704581',
  'rw5704582',
  'rw5704583',
  'rw5704584',
  'rw5704586',
  'rw5704587',
  'rw5704589',
  'rw5704588',
  'rw5704591',
  'rw5704590',
  'rw5704594',
  'rw5704595',
  'rw5704596',
  'rw5704597',
  'rw5704598',
  'rw5704599',
  'rw5704600',
  'rw5704601',
  'rw5704602',
  'rw5704603',
  'rw5704604',
  'rw5704605',
  'rw5704606',
  'rw5704607',
  'rw5704609',
  'rw5704610',
  'rw5704611',
  'rw5704612',
  'rw5704613',
  'rw5704614',
  'rw5704615',
  'rw5704617',
  'rw5704618',
  'rw5704620',
  'rw5704619',
  'rw5704621',
  'rw5704623',
  'rw5704624',
  'rw5704625',
  'rw5704626',
  'rw5704627',
  'rw5704628',
  'rw5704629',
  'rw5704630',
  'rw5704631',
  'rw5704632',
  'rw5704633',
  'rw5704634',
  'rw5704635',
  'rw5704636',
  'rw5704638',
  'rw5704637',
  'rw5704640',
  'rw5704639',
  'rw5704641',
  'rw5704642',
  'rw5704644',
  'rw5704645',
  'rw5704646',
  'rw5704649',
  'rw5704650',
  'rw5704651',
  'rw5704652',
  'rw5704653',
  'rw5704654',
  'rw5704656',
  'rw5704657',
  'rw5704658',
  'rw5704659',
  'rw5704660',
  'rw5704661',
  'rw5704662',
  'rw5704663',
  'rw5704664',
  'rw5704665',
  'rw5704666',
  'rw5704667',
  'rw5704668',
  'rw5704669',
  'rw5704671',
  'rw5704672',
  'rw5704673',
  'rw5704675',
  'rw5704676',
  'rw5704677',
  'rw5704680',
  'rw5704679',
  'rw5704681',
  'rw5704682',
  'rw5704683',
  'rw5704684',
  'rw5704685',
  'rw5704686',
  'rw5704687',
  'rw5704688',
  'rw5704689',
  'rw5704690',
  'rw5704692',
  'rw5704691',
  'rw5704693',
  'rw5704694',
  'rw5704696',
  'rw5704695',
  'rw5704697',
  'rw5704700',
  'rw5704701',
  'rw5704702',
  'rw5704703',
  'rw5704705',
  'rw5704704',
  'rw5704706',
  'rw5704708',
  'rw5704709',
  'rw5704711',
  'rw5704714',
  'rw5704713',
  'rw5704716',
  'rw5704715',
  'rw5704718',
  'rw5704717',
  'rw5704720',
  'rw5704719',
  'rw5704721',
  'rw5704723',
  'rw5704724',
  'rw5704725',
  'rw5704726',
  'rw5704727',
  'rw5704728',
  'rw5704729',
  'rw5704730',
  'rw5704731',
  'rw5704733',
  'rw5704734',
  'rw5704735',
  'rw5704736',
  'rw5704738',
  'rw5704739',
  'rw5704740',
  'rw5704741',
  'rw5704743',
  'rw5704745',
  'rw5704746',
  'rw5704747',
  'rw5704748',
  'rw5704749',
  'rw5704750',
  'rw5704751',
  'rw5704752',
  'rw5704753',
  'rw5704754',
  'rw5704755',
  'rw5704756',
  'rw5704758',
  'rw5704759',
  'rw5704760',
  'rw5704761',
  'rw5704763',
  'rw5704764',
  'rw5704765',
  'rw5704766',
  'rw5704767',
  'rw5704768',
  'rw5704769',
  'rw5704770',
  'rw5704771',
  'rw5704773',
  'rw5704774',
  'rw5704775',
  'rw5704776',
  'rw5704779',
  'rw5704780',
  'rw5704781',
  'rw5704782',
  'rw5704785',
  'rw5704784',
  'rw5704786',
  'rw5704789',
  'rw5704791',
  'rw5704792',
  'rw5704793',
  'rw5704794',
  'rw5704795',
  'rw5704797',
  'rw5704798',
  'rw5704799',
  'rw5704800',
  'rw5704801',
  'rw5704802',
  'rw5704803',
  'rw5704804',
  'rw5704805',
  'rw5704806',
  'rw5704807',
  'rw5704808',
  'rw5704809',
  'rw5704811',
  'rw5704812',
  'rw5704814',
  'rw5704813',
  'rw5704815',
  'rw5704816',
  'rw5704817',
  'rw5704818',
  'rw5704819',
  'rw5704821',
  'rw5704823',
  'rw5704824',
  'rw5704825',
  'rw5704826',
  'rw5704827',
  'rw5704831',
  'rw5704832',
  'rw5704833',
  'rw5704834',
  'rw5704835',
  'rw5704836',
  'rw5704837',
  'rw5704839',
  'rw5704840',
  'rw5704841',
  'rw5704842',
  'rw5704843',
  'rw5704844',
  'rw5704845',
  'rw5704846',
  'rw5704847',
  'rw5704848',
  'rw5704849',
  'rw5704850',
  'rw5704851',
  'rw5704852',
  'rw5704853',
  'rw5704855',
  'rw5704856',
  'rw5704858',
  'rw5704857',
  'rw5704859',
  'rw5704860',
  'rw5704862',
  'rw5704861',
  'rw5704863',
  'rw5704864',
  'rw5704866',
  'rw5704865',
  'rw5704868',
  'rw5704867',
  'rw5704870',
  'rw5704871',
  'rw5704873',
  'rw5704876',
  'rw5704877',
  'rw5704880',
  'rw5704881',
  'rw5704882',
  'rw5704883',
  'rw5704884',
  'rw5704885',
  'rw5704886',
  'rw5704887',
  'rw5704888',
  'rw5704889',
  'rw5704890',
  'rw5704891',
  'rw5704892',
  'rw5704893',
  'rw5704894',
  'rw5704895',
  'rw5704896',
  'rw5704897',
  'rw5704898',
  'rw5704899',
  'rw5704900',
  'rw5704902',
  'rw5704904',
  'rw5704905',
  'rw5704907',
  'rw5704906',
  'rw5704910',
  'rw5704912',
  'rw5704913',
  'rw5704917',
  'rw5704918',
  'rw5704919',
  'rw5704922',
  'rw5704921',
  'rw5704924',
  'rw5704923',
  'rw5704926',
  'rw5704928',
  'rw5704927',
  'rw5704929',
  'rw5704931',
  'rw5704932',
  'rw5704933',
  'rw5704935',
  'rw5704936',
  'rw5704938',
  'rw5704937',
  'rw5704940',
  'rw5704939',
  'rw5704941',
  'rw5704942',
  'rw5704943',
  'rw5704944',
  'rw5704945',
  'rw5704946',
  'rw5704948',
  'rw5704949',
  'rw5704950',
  'rw5704952',
  'rw5704953',
  'rw5704954',
  'rw5704955',
  'rw5704957',
  'rw5704958',
  'rw5704960',
  'rw5704961',
  'rw5704962',
  'rw5704963',
  'rw5704964',
  'rw5704965',
  'rw5704966',
  'rw5704967',
  'rw5704969',
  'rw5704970',
  'rw5704973',
  'rw5704974',
  'rw5704975',
  'rw5704976',
  'rw5704977',
  'rw5704979',
  'rw5704984',
  'rw5704985',
  'rw5704986',
  'rw5704987',
  'rw5704988',
  'rw5704989',
  'rw5704990',
  'rw5704992',
  'rw5704993',
  'rw5704994',
  'rw5704995',
  'rw5704997',
  'rw5704996',
  'rw5705001',
  'rw5705000',
  'rw5705004',
  'rw5705005',
  'rw5705006',
  'rw5705007',
  'rw5705008',
  'rw5705009',
  'rw5705011',
  'rw5705014',
  'rw5705013',
  'rw5705015',
  'rw5705018',
  'rw5705019',
  'rw5705020',
  'rw5705021',
  'rw5705022',
  'rw5705025',
  'rw5705028',
  'rw5705030',
  'rw5705031',
  'rw5705033',
  'rw5705032',
  'rw5705034',
  'rw5705038',
  'rw5705040',
  'rw5705041',
  'rw5705042',
  'rw5705043',
  'rw5705044',
  'rw5705045',
  'rw5705046',
  'rw5705047',
  'rw5705048',
  'rw5705049',
  'rw5705050',
  'rw5705051',
  'rw5705052',
  'rw5705054',
  'rw5705055',
  'rw5705056',
  'rw5705057',
  'rw5705058',
  'rw5705059',
  'rw5705060',
  'rw5705061',
  'rw5705062',
  'rw5705063',
  'rw5705064',
  'rw5705065',
  'rw5705067',
  'rw5705068',
  'rw5705069',
  'rw5705071',
  'rw5705072',
  'rw5705074',
  'rw5705076',
  'rw5705078',
  'rw5705079',
  'rw5705085',
  'rw5705088',
  'rw5705087',
  'rw5705090',
  'rw5705089',
  'rw5705091',
  'rw5705094',
  'rw5705095',
  'rw5705096',
  'rw5705097',
  'rw5705098',
  'rw5705099',
  'rw5705100',
  'rw5705101',
  'rw5705102',
  'rw5705103',
  'rw5705105',
  'rw5705106',
  'rw5705107',
  'rw5705108',
  'rw5705109',
  'rw5705110',
  'rw5705111',
  'rw5705112',
  'rw5705113',
  'rw5705115',
  'rw5705117',
  'rw5705118',
  'rw5705119',
  'rw5705120',
  'rw5705121',
  'rw5705122',
  'rw5705123',
  'rw5705124',
  'rw5705128',
  'rw5705129',
  'rw5705131',
  'rw5705132',
  'rw5705134',
  'rw5705135',
  'rw5705136',
  'rw5705137',
  'rw5705140',
  'rw5705139',
  'rw5705141',
  'rw5705142',
  'rw5705143',
  'rw5705144',
  'rw5705145',
  'rw5705146',
  'rw5705147',
  'rw5705148',
  'rw5705149',
  'rw5705150',
  'rw5705151',
  'rw5705152',
  'rw5705153',
  'rw5705156',
  'rw5705157',
  'rw5705158',
  'rw5705159',
  'rw5705161',
  'rw5705163',
  'rw5705164',
  'rw5705165',
  'rw5705167',
  'rw5705168',
  'rw5705169',
  'rw5705170',
  'rw5705171',
  'rw5705172',
  'rw5705173',
  'rw5705174',
  'rw5705175',
  'rw5705176',
  'rw5705178',
  'rw5705180',
  'rw5705181',
  'rw5705182',
  'rw5705183',
  'rw5705184',
  'rw5705185',
  'rw5705187',
  'rw5705186',
  'rw5705189',
  'rw5705188',
  'rw5705191',
  'rw5705190',
  'rw5705192',
  'rw5705193',
  'rw5705194',
  'rw5705196',
  'rw5705197',
  'rw5705198',
  'rw5705199',
  'rw5705200',
  'rw5705202',
  'rw5705203',
  'rw5705204',
  'rw5705206',
  'rw5705207',
  'rw5705208',
  'rw5705209',
  'rw5705210',
  'rw5705212',
  'rw5705213',
  'rw5705215',
  'rw5705216',
  'rw5705217',
  'rw5705219',
  'rw5705220',
  'rw5705221',
  'rw5705224',
  'rw5705223',
  'rw5705226',
  'rw5705225',
  'rw5705228',
  'rw5705227',
  'rw5705229',
  'rw5705231',
  'rw5705232',
  'rw5705234',
  'rw5705235',
  'rw5705236',
  'rw5705239',
  'rw5705238',
  'rw5705240',
  'rw5705242',
  'rw5705243',
  'rw5705244',
  'rw5705245',
  'rw5705246',
  'rw5705247',
  'rw5705250',
  'rw5705249',
  'rw5705251',
  'rw5705252',
  'rw5705253',
  'rw5705256',
  'rw5705258',
  'rw5705259',
  'rw5705263',
  'rw5705264',
  'rw5705267',
  'rw5705268',
  'rw5705269',
  'rw5705270',
  'rw5705272',
  'rw5705273',
  'rw5705274',
  'rw5705275',
  'rw5705276',
  'rw5705277',
  'rw5705278',
  'rw5705280',
  'rw5705283',
  'rw5705284',
  'rw5705286',
  'rw5705287',
  'rw5705288',
  'rw5705289',
  'rw5705290',
  'rw5705291',
  'rw5705292',
  'rw5705293',
  'rw5705294',
  'rw5705295',
  'rw5705297',
  'rw5705298',
  'rw5705299',
  'rw5705300',
  'rw5705301',
  'rw5705302',
  'rw5705303',
  'rw5705304',
  'rw5705305',
  'rw5705306',
  'rw5705308',
  'rw5705309',
  'rw5705310',
  'rw5705312',
  'rw5705313',
  'rw5705314',
  'rw5705315',
  'rw5705316',
  'rw5705317',
  'rw5705318',
  'rw5705319',
  'rw5705320',
  'rw5705322',
  'rw5705323',
  'rw5705325',
  'rw5705326',
  'rw5705327',
  'rw5705330',
  'rw5705329',
  'rw5705332',
  'rw5705333',
  'rw5705334',
  'rw5705336',
  'rw5705337',
  'rw5705338',
  'rw5705339',
  'rw5705340',
  'rw5705341',
  'rw5705342',
  'rw5705343',
  'rw5705346',
  'rw5705347',
  'rw5705348',
  'rw5705350',
  'rw5705349',
  'rw5705351',
  'rw5705352',
  'rw5705355',
  'rw5705356',
  'rw5705357',
  'rw5705360',
  'rw5705362',
  'rw5705363',
  'rw5705364',
  'rw5705365',
  'rw5705366',
  'rw5705367',
  'rw5705368',
  'rw5705369',
  'rw5705370',
  'rw5705371',
  'rw5705372',
  'rw5705374',
  'rw5705375',
  'rw5705376',
  'rw5705378',
  'rw5705379',
  'rw5705381',
  'rw5705382',
  'rw5705383',
  'rw5705384',
  'rw5705385',
  'rw5705386',
  'rw5705387',
  'rw5705388',
  'rw5705389',
  'rw5705390',
  'rw5705391',
  'rw5705392',
  'rw5705393',
  'rw5705396',
  'rw5705397',
  'rw5705398',
  'rw5705399',
  'rw5705400',
  'rw5705401',
  'rw5705402',
  'rw5705404',
  'rw5705405',
  'rw5705406',
  'rw5705407',
  'rw5705408',
  'rw5705409',
  'rw5705410',
  'rw5705411',
  'rw5705412',
  'rw5705413',
  'rw5705415',
  'rw5705416',
  'rw5705417',
  'rw5705418',
  'rw5705419',
  'rw5705420',
  'rw5705421',
  'rw5705423',
  'rw5705424',
  'rw5705426',
  'rw5705425',
  'rw5705427',
  'rw5705429',
  'rw5705430',
  'rw5705431',
  'rw5705433',
  'rw5705434',
  'rw5705435',
  'rw5705437',
  'rw5705439',
  'rw5705440',
  'rw5705442',
  'rw5705441',
  'rw5705443',
  'rw5705444',
  'rw5705445',
  'rw5705446',
  'rw5705447',
  'rw5705448',
  'rw5705449',
  'rw5705450',
  'rw5705451',
  'rw5705452',
  'rw5705453',
  'rw5705454',
  'rw5705455',
  'rw5705456',
  'rw5705457',
  'rw5705458',
  'rw5705459',
  'rw5705460',
  'rw5705462',
  'rw5705461',
  'rw5705463',
  'rw5705464',
  'rw5705466',
  'rw5705465',
  'rw5705468',
  'rw5705467',
  'rw5705469',
  'rw5705470',
  'rw5705471',
  'rw5705472',
  'rw5705473',
  'rw5705474',
  'rw5705476',
  'rw5705477',
  'rw5705478',
  'rw5705479',
  'rw5705481',
  'rw5705482',
  'rw5705483',
  'rw5705484',
  'rw5705485',
  'rw5705486',
  'rw5705487',
  'rw5705488',
  'rw5705489',
  'rw5705490',
  'rw5705491',
  'rw5705495',
  'rw5705496',
  'rw5705497',
  'rw5705498',
  'rw5705500',
  'rw5705499',
  'rw5705502',
  'rw5705504',
  'rw5705505',
  'rw5705507',
  'rw5705506',
  'rw5705508',
  'rw5705509',
  'rw5705511',
  'rw5705512',
  'rw5705514',
  'rw5705515',
  'rw5705516',
  'rw5705517',
  'rw5705518',
  'rw5705520',
  'rw5705521',
  'rw5705522',
  'rw5705523',
  'rw5705524',
  'rw5705525',
  'rw5705526',
  'rw5705528',
  'rw5705529',
  'rw5705530',
  'rw5705531',
  'rw5705532',
  'rw5705533',
  'rw5705535',
  'rw5705534',
  'rw5705536',
  'rw5705537',
  'rw5705538',
  'rw5705539',
  'rw5705540',
  'rw5705541',
  'rw5705542',
  'rw5705543',
  'rw5705544',
  'rw5705549',
  'rw5705548',
  'rw5705551',
  'rw5705550',
  'rw5705552',
  'rw5705553',
  'rw5705555',
  'rw5705556',
  'rw5705557',
  'rw5705558',
  'rw5705559',
  'rw5705560',
  'rw5705561',
  'rw5705562',
  'rw5705563',
  'rw5705564',
  'rw5705566',
  'rw5705567',
  'rw5705568',
  'rw5705572',
  'rw5705571',
  'rw5705574',
  'rw5705576',
  'rw5705577',
  'rw5705578',
  'rw5705580',
  'rw5705581',
  'rw5705582',
  'rw5705584',
  'rw5705586',
  'rw5705587',
  'rw5705589',
  'rw5705590',
  'rw5705591',
  'rw5705592',
  'rw5705593',
  'rw5705594',
  'rw5705595',
  'rw5705597',
  'rw5705598',
  'rw5705600',
  'rw5705599',
  'rw5705602',
  'rw5705603',
  'rw5705604',
  'rw5705605',
  'rw5705606',
  'rw5705607',
  'rw5705609',
  'rw5705610',
  'rw5705611',
  'rw5705612',
  'rw5705613',
  'rw5705615',
  'rw5705616',
  'rw5705617',
  'rw5705618',
  'rw5705619',
  'rw5705620',
  'rw5705621',
  'rw5705622',
  'rw5705623',
  'rw5705624',
  'rw5705625',
  'rw5705626',
  'rw5705627',
  'rw5705628',
  'rw5705629',
  'rw5705630',
  'rw5705631',
  'rw5705633',
  'rw5705635',
  'rw5705634',
  'rw5705637',
  'rw5705639',
  'rw5705640',
  'rw5705641',
  'rw5705642',
  'rw5705643',
  'rw5705645',
  'rw5705646',
  'rw5705647',
  'rw5705648',
  'rw5705651',
  'rw5705650',
  'rw5705653',
  'rw5705654',
  'rw5705655',
  'rw5705656',
  'rw5705657',
  'rw5705658',
  'rw5705659',
  'rw5705660',
  'rw5705661',
  'rw5705663',
  'rw5705664',
  'rw5705665',
  'rw5705666',
  'rw5705667',
  'rw5705668',
  'rw5705669',
  'rw5705670',
  'rw5705671',
  'rw5705672',
  'rw5705674',
  'rw5705675',
  'rw5506445',
  'rw5506446',
  'rw5506447',
  'rw5506449',
  'rw5506450',
  'rw5506451',
  'rw5506452',
  'rw5506453',
  'rw5506454',
  'rw5506455',
  'rw5506456',
  'rw5506457',
  'rw5506458',
  'rw5506459',
  'rw5506460',
  'rw5506461',
  'rw5506462',
  'rw5506463',
  'rw5506464',
  'rw5506465',
  'rw5506466',
  'rw5506468',
  'rw5506467',
  'rw5506469',
  'rw5506471',
  ...],
 'movie': ['After Life (2019– )',
  'The Valhalla Murders (2019– )',
  'Special OPS (2020– )',
  '#BlackAF (2020– )',
  'The Droving (2020)',
  'All About Eve (1950)',
  'Runaway Train (1985)',
  'Iron Fist (2017–2018)',
  'The Half of It (I) (2020)',
  'This Is Us (2016– )',
  'Closure (I) (2018)',
  'Unstoppable (2010)',
  'Beastie Boys Story (2020)',
  'Ruben Brandt, Collector (2018)',
  'Some Kind of Hate (2015)',
  'Cube Zero (2004)',
  'Carne (1991)',
  '500 Days of Summer (2009)',
  '8½ (1963)',
  'Glimpses of New Scotland (1947)',
  'The Master (2012)',
  'Thappad (I) (2020)',
  'Matchmaker Mysteries: A Fatal Romance (2020) Season 1, Episode 2',
  'Dangerous Lies (2020)',
  'Brooklyn Nine-Nine (2013– )',
  'After Life (2019– )',
  "Fool's Gold (I) (2008)",
  'The Raikar Case (2020– )',
  'Vida (2018–2020)',
  'Airplane Mode (II) (2019)',
  'Bloodline: Part 13 (2015) Season 1, Episode 13',
  'Once Upon a Time in London (2019)',
  'Jia you er nü (2005– )',
  'Hollywood (2020)',
  'After Life (2019– )',
  'Four More Shots Please (2019– )',
  'Kingdom (2019– )',
  'Sonic the Hedgehog (2020)',
  'For the Love of Jessee (2020)',
  'Trying (2020)',
  'Red Joan (2018)',
  'The Wandering Earth (2019)',
  'The Chosen (2017– )',
  'Mrs. Serial Killer (2020)',
  'The Art of Racing in the Rain (2019)',
  'Upload (2020– )',
  'Battle Los Angeles (2011)',
  'Hunters (2020– )',
  'Roped (2020)',
  'Sonic the Hedgehog (2020)',
  'Brightburn (2019)',
  'Outer Banks (2020– )',
  'Battle Los Angeles (2011)',
  'The Field Guide to Evil (2018)',
  'Code 404 (2020– )',
  'What Love Looks Like (2020)',
  'Memento (2000)',
  'The Invisible Man (2017)',
  'For the Love of Jessee (2020)',
  'Hundred (2020– )',
  'Billions: The New Decas (2020) Season 5, Episode 1',
  'Mannix (1967–1975)',
  'Little Fires Everywhere (2020)',
  'Midsomer Murders: The Axeman Cometh (2007) Season 10, Episode 4',
  'Tales from the Loop (2020– )',
  'Dakota Incident (1956)',
  'Mrs. Serial Killer (2020)',
  'How I Met Your Mother: 46 Minutes (2012) Season 7, Episode 14',
  'Laverne & Shirley: The Survival Test (1980) Season 5, Episode 22',
  'Prey (V) (2019)',
  'Memento Mori (II) (2018)',
  'Charade (1963)',
  'Batwoman: Grinning from Ear to Ear (2020) Season 1, Episode 14',
  'Trolls World Tour (2020)',
  'Arachnophobia (1990)',
  'Jojo Rabbit (2019)',
  'Hollywood (2020)',
  'Lost Child (2017)',
  'Halloween III: Season of the Witch (1982)',
  'Normal People (2020)',
  'Book of Mormon Videos (2019–2021)',
  'Like a Boss (2020)',
  'The Reliant (2019)',
  'The Twilight Zone: Where Is Everybody? (1959) Season 1, Episode 1',
  'Upload (2020– )',
  'After Life (2019– )',
  'Rapid Exchange (2003 Video)',
  'The Visit (I) (2015)',
  'Laverne & Shirley: The Duke of Squigman (1980) Season 5, Episode 23',
  'Behind the Curve (2018)',
  'Mean Girls (2004)',
  'Turistas (2006)',
  'Light from the Tower (2020)',
  'Spider-Man 3 (2007)',
  'After Life (2019– )',
  'Doom: Annihilation (2019)',
  'Apocalypse Now (1979)',
  'Call for Dreams (2018)',
  'The Wretched (2019)',
  'Star Trek: Picard (2020– )',
  'Legacies (2018– )',
  'Megamind (2010)',
  'The 100 (2014–2020)',
  'Laverne & Shirley: Antonio, the Amazing (1980) Season 5, Episode 24',
  'Upload (2020– )',
  'Normal People (2020)',
  'Man in the Wilderness (1971)',
  'The Meg (2018)',
  'Cruel and Unusual Therapy (2020)',
  'Colonia (2015)',
  'Hollywood (2020)',
  'The Oregonian (2011)',
  'Bloody Birthday (1981)',
  'The Murders at White House Farm (2020)',
  'Star Wars: The Clone Wars: Victory and Death (2020) Season 7, Episode 12',
  'El Dragón: Return of a Warrior (2019–2020)',
  'The United States of Leland (2003)',
  'Cobra (2020–2021)',
  'Sonic the Hedgehog (2020)',
  'Heroic Losers (2019)',
  'TRON (1982)',
  'The King of Marvin Gardens (1972)',
  'Hollywood (2020)',
  'Star Wars: The Clone Wars: Victory and Death (2020) Season 7, Episode 12',
  'The Hunger Games (2012)',
  'The Judge (2014)',
  'The Banker (2020)',
  'The Redeeming (2018)',
  'Thappad (I) (2020)',
  'Dreamkatcher (2020)',
  'Normal People (2020)',
  'Never Have I Ever (2020– )',
  'Family Karma (2020– )',
  'Into the Wild (2007)',
  'One Day: Justice Delivered (2019)',
  'Circle (II) (2015)',
  'Troop Zero (2019)',
  '12 Monkeys (2015–2018)',
  'Donnybrook (2018)',
  'Normal People (2020)',
  'Jigsaw (I) (2017)',
  'The English Game (2020– )',
  'Jumanji: The Next Level (2019)',
  'Gangs of London (2020– )',
  'Full Metal Jacket (1987)',
  'Blinded by the Light (2019)',
  'The Predator (2018)',
  'Star Wars: The Clone Wars: Victory and Death (2020) Season 7, Episode 12',
  'Hunters (2020– )',
  'Dangerous Lies (2020)',
  'Star Wars: The Clone Wars: Victory and Death (2020) Season 7, Episode 12',
  'Ek Nirnay... Swatahacha Swatasathi (2019)',
  'Anne with an E (2017–2019)',
  'Jumanji: Welcome to the Jungle (2017)',
  'When They See Us (2019)',

In [46]:
jumlah_film_min_pos = {}

for i in range(len(d_data["review_id"])) :
    if d_data["rating"][i] <= 5 :
        rate = "1-5"
    else :
        rate = "6-10"
    format_film = f"{rate} {d_data['movie'][i]}"
    
    if format_film not in jumlah_film_min_pos :
        jumlah_film_min_pos[format_film] = 1
    else :
        jumlah_film_min_pos[format_film] += 1

In [47]:
data_sampling20 = {"review_id" : [], "movie" : [], "rating" : [] , "review_detail" : []}
counter_sampling = {}

for i in range(len(d_data["review_id"])) :
    if d_data["rating"][i] <= 5 :
        rate = "1-5"
    else :
        rate = "6-10"
    format_film = f"{rate} {d_data['movie'][i]}"
    
    if format_film not in counter_sampling :
        counter_sampling[format_film] = 1
        for j in d_data :
            data_sampling20[j].append(d_data[j][i])
    elif counter_sampling[format_film] < jumlah_film_min_pos[format_film]//5 :
        counter_sampling[format_film] += 1
        for j in d_data :
            data_sampling20[j].append(d_data[j][i])
    else :
        continue
    
df_data_sampling = pd.DataFrame(data_sampling20)

df_data_sampling.head()

,review_id,movie,rating,review_detail
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t..."
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ..."
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...

In [48]:
ukuran_data_sampling = df_data_sampling.shape[0]
ukuran_data_sampling

295357

In [49]:
ukuran_data_sampling/ukuran_data

0.3080572773743107

## Cek Representatif Data Sampling

In [50]:
jumlah = {"0-5" : 0 , "5-10" : 0}

for i in d_data["rating"] :
    if i is None :
        continue
    if i < 5 :
        jumlah["0-5"] += 1
    elif i > 6 :
        jumlah["5-10"] += 1
        
print(jumlah)
neg1 = jumlah["0-5"]/(jumlah["0-5"]+jumlah["5-10"])
print(neg1)

{'0-5': 241903, '5-10': 583733}
0.2929898890067778

In [51]:
jumlah = {"0-5" : 0 , "5-10" : 0}

for i in data_sampling20["rating"] :
    if i is None :
        continue
    if i < 5 :
        jumlah["0-5"] += 1
    elif i > 6 :
        jumlah["5-10"] += 1
        
print(jumlah)
neg2 = jumlah["0-5"]/(jumlah["0-5"]+jumlah["5-10"])
print(neg2)

{'0-5': 74396, '5-10': 171907}
0.30205072613813067

In [52]:
neg2-neg1

0.009060837131352861

In [53]:
persen_per_film = {}
for i in counter_sampling :
    persen_per_film[i] = counter_sampling[i]/jumlah_film_min_pos[i]
    
avg_persen_film = sum(list(persen_per_film.values()))/len(list(persen_per_film.values()))
avg_persen_film

0.7230351663631615

In [54]:
pd.DataFrame(df_data_sampling).to_csv("data_sampling20.csv",index=False)

In [55]:
del df_data_sampling["review_id"]
del df_data_sampling["movie"]
del df_data_sampling["rating"]

df_data_sampling.head()

                                       review_detail
0  I enjoyed the first season, but I must say I t...
1  I know Iceland is a small country and police d...
2  Except K K , no other actor looks comfortable ...
3  I'm guessing that as a 62 year old white woman...
4  Here's the truth. There's not much to this mov...

In [56]:
pd.DataFrame(df_data_sampling).to_csv("data_sampling20_komen.csv",index=False)

In [57]:
df_data_sampling = pd.read_csv("data_sampling20.csv")
df_data_sampling

,review_id,movie,rating,review_detail
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t..."
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ..."
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...
...,...,...,...,...
295352,rw0982960,General Spanky (1936),5.0,When I first saw this obscure film--the ONLY f...
295353,rw0982972,Timecop: The Berlin Decision (2003 Video),5.0,I caught this film on SciFi Channel at midnigh...
295354,rw0982974,Tibet: Cry of the Snow Lion (2002),10.0,"From this poignant film, we learn how Richard ..."
295355,rw0982977,Vinyl (2000),2.0,i wish the show had had real audiophiles inste...
295356,rw0982985,Solas (1999),10.0,I only just watched this film for the first ti...

## Memulai Labeling Negatif Positif BERT

In [58]:
import torch
import pandas as pd
from transformers import pipeline
from tqdm import tqdm
from datetime import datetime
import os

device = 0 if torch.cuda.is_available() else -1
print(f"Proses dijalankan menggunakan: {'GPU' if device == 0 else 'CPU'}")

pretrained_model = "distilbert-base-uncased-finetuned-sst-2-english"

nlp_detector = pipeline("sentiment-analysis", model=pretrained_model, device=device, batch_size=8)

list_komentar_anda = list(df_data_sampling["review_detail"])
output_csv = "data_komen_sampling20_pluslabel_distilbert.csv"

chunk_size = 1000
total_data = len(list_komentar_anda)

print("Memulai pelabelan dengan metode manual slicing...")

waktu1 = datetime.now()
print(f"NLPD Start : {waktu1}")

for i in tqdm(range(0, total_data, chunk_size)):
    potongan_list = list_komentar_anda[i : i + chunk_size]
    
    hasil_potongan = nlp_detector(potongan_list, truncation=True, max_length=512)
    
    data_buffer = []
    for teks, res in zip(potongan_list, hasil_potongan):
        data_buffer.append({
            'review_detail': teks,
            'sentiment_label': res['label'],
            'confidence_score': res['score']
        })
    
    df_chunk = pd.DataFrame(data_buffer)
    if not os.path.isfile(output_csv):
        df_chunk.to_csv(output_csv, index=False)
    else:
        df_chunk.to_csv(output_csv, mode='a', header=False, index=False)
        
    torch.cuda.empty_cache()

waktu2 = datetime.now()
print(f"\nNLPD Finish : {waktu2}")
print(f"Waktu Proses : {waktu2 - waktu1}")
print(f"Semua data berhasil dilabeli dan disimpan di: {output_csv}")

Proses dijalankan menggunakan: GPU

Device set to use cuda:0

Memulai pelabelan dengan metode manual slicing...
NLPD Start : 2026-06-15 05:48:42.364727

100%|██████████| 296/296 [40:25<00:00,  8.19s/it]

NLPD Finish : 2026-06-15 06:29:07.418825
Waktu Proses : 0:40:25.054098
Semua data berhasil dilabeli dan disimpan di: data_komen_sampling20_pluslabel_distilbert.csv

In [59]:
device = 0 if torch.cuda.is_available() else -1
print(f"Proses dijalankan menggunakan: {'GPU' if device == 0 else 'CPU'}")

pretrained_model = "siebert/sentiment-roberta-large-english"

nlp_detector = pipeline("sentiment-analysis", model=pretrained_model, device=device, batch_size=8)

list_komentar_anda = list(df_data_sampling["review_detail"])
output_csv = "data_komen_sampling20_pluslabel_siebertroberta.csv"

chunk_size = 1000
total_data = len(list_komentar_anda)

print("Memulai pelabelan dengan metode manual slicing...")

waktu1 = datetime.now()
print(f"NLPD Start : {waktu1}")

for i in tqdm(range(0, total_data, chunk_size)):
    potongan_list = list_komentar_anda[i : i + chunk_size]
    
    hasil_potongan = nlp_detector(potongan_list, truncation=True, max_length=512)
    
    data_buffer = []
    for teks, res in zip(potongan_list, hasil_potongan):
        data_buffer.append({
            'review_detail': teks,
            'sentiment_label': res['label'],
            'confidence_score': res['score']
        })
    
    df_chunk = pd.DataFrame(data_buffer)
    if not os.path.isfile(output_csv):
        df_chunk.to_csv(output_csv, index=False)
    else:
        df_chunk.to_csv(output_csv, mode='a', header=False, index=False)
        
    torch.cuda.empty_cache()

waktu2 = datetime.now()
print(f"\nNLPD Finish : {waktu2}")
print(f"Waktu Proses : {waktu2 - waktu1}")
print(f"Semua data berhasil dilabeli dan disimpan di: {output_csv}")

Proses dijalankan menggunakan: GPU

Device set to use cuda:0

Memulai pelabelan dengan metode manual slicing...
NLPD Start : 2026-06-15 06:29:11.382850

100%|██████████| 296/296 [4:13:26<00:00, 51.37s/it]

NLPD Finish : 2026-06-15 10:42:37.824635
Waktu Proses : 4:13:26.441785
Semua data berhasil dilabeli dan disimpan di: data_komen_sampling20_pluslabel_siebertroberta.csv

In [60]:
device = 0 if torch.cuda.is_available() else -1
print(f"Proses dijalankan menggunakan: {'GPU' if device == 0 else 'CPU'}")

pretrained_model = "textattack/bert-base-uncased-SST-2"

nlp_detector = pipeline("sentiment-analysis", model=pretrained_model, device=device, batch_size=8)

list_komentar_anda = list(df_data_sampling["review_detail"])
output_csv = "data_komen_sampling20_pluslabel_textattackbert.csv"

chunk_size = 1000
total_data = len(list_komentar_anda)

print("Memulai pelabelan dengan metode manual slicing...")

waktu1 = datetime.now()
print(f"NLPD Start : {waktu1}")

for i in tqdm(range(0, total_data, chunk_size)):
    potongan_list = list_komentar_anda[i : i + chunk_size]
    
    hasil_potongan = nlp_detector(potongan_list, truncation=True, max_length=512)
    
    data_buffer = []
    for teks, res in zip(potongan_list, hasil_potongan):
        data_buffer.append({
            'review_detail': teks,
            'sentiment_label': res['label'],
            'confidence_score': res['score']
        })
    
    df_chunk = pd.DataFrame(data_buffer)
    if not os.path.isfile(output_csv):
        df_chunk.to_csv(output_csv, index=False)
    else:
        df_chunk.to_csv(output_csv, mode='a', header=False, index=False)
        
    torch.cuda.empty_cache()

waktu2 = datetime.now()
print(f"\nNLPD Finish : {waktu2}")
print(f"Waktu Proses : {waktu2 - waktu1}")
print(f"Semua data berhasil dilabeli dan disimpan di: {output_csv}")

Proses dijalankan menggunakan: GPU

Device set to use cuda:0

Memulai pelabelan dengan metode manual slicing...
NLPD Start : 2026-06-15 10:42:45.204237

  2%|▏         | 5/296 [01:35<1:32:26, 19.06s/it]

KeyboardInterrupt:

In [ ]:
device = 0 if torch.cuda.is_available() else -1
print(f"Proses dijalankan menggunakan: {'GPU' if device == 0 else 'CPU'}")

pretrained_model = "mrm8488/deberta-v3-small-finetuned-sst2"

nlp_detector = pipeline("sentiment-analysis", model=pretrained_model, device=device, batch_size=8)

list_komentar_anda = list(df_data_sampling["review_detail"])
output_csv = "data_komen_sampling20_pluslabel_mrmdeberta.csv"

chunk_size = 1000
total_data = len(list_komentar_anda)

print("Memulai pelabelan dengan metode manual slicing...")

waktu1 = datetime.now()
print(f"NLPD Start : {waktu1}")

for i in tqdm(range(0, total_data, chunk_size)):
    potongan_list = list_komentar_anda[i : i + chunk_size]
    
    hasil_potongan = nlp_detector(potongan_list, truncation=True, max_length=512)
    
    data_buffer = []
    for teks, res in zip(potongan_list, hasil_potongan):
        data_buffer.append({
            'review_detail': teks,
            'sentiment_label': res['label'],
            'confidence_score': res['score']
        })
    
    df_chunk = pd.DataFrame(data_buffer)
    if not os.path.isfile(output_csv):
        df_chunk.to_csv(output_csv, index=False)
    else:
        df_chunk.to_csv(output_csv, mode='a', header=False, index=False)
        
    torch.cuda.empty_cache()

waktu2 = datetime.now()
print(f"\nNLPD Finish : {waktu2}")
print(f"Waktu Proses : {waktu2 - waktu1}")
print(f"Semua data berhasil dilabeli dan disimpan di: {output_csv}")

In [ ]:
device = 0 if torch.cuda.is_available() else -1
print(f"Proses dijalankan menggunakan: {'GPU' if device == 0 else 'CPU'}")

pretrained_model = "textattack/roberta-base-SST-2"

nlp_detector = pipeline("sentiment-analysis", model=pretrained_model, device=device, batch_size=8)

list_komentar_anda = list(df_data_sampling["review_detail"])
output_csv = "data_komen_sampling20_pluslabel_textattackroberta.csv"

chunk_size = 1000
total_data = len(list_komentar_anda)

print("Memulai pelabelan dengan metode manual slicing...")

waktu1 = datetime.now()
print(f"NLPD Start : {waktu1}")

for i in tqdm(range(0, total_data, chunk_size)):
    potongan_list = list_komentar_anda[i : i + chunk_size]
    
    hasil_potongan = nlp_detector(potongan_list, truncation=True, max_length=512)
    
    data_buffer = []
    for teks, res in zip(potongan_list, hasil_potongan):
        data_buffer.append({
            'review_detail': teks,
            'sentiment_label': res['label'],
            'confidence_score': res['score']
        })
    
    df_chunk = pd.DataFrame(data_buffer)
    if not os.path.isfile(output_csv):
        df_chunk.to_csv(output_csv, index=False)
    else:
        df_chunk.to_csv(output_csv, mode='a', header=False, index=False)
        
    torch.cuda.empty_cache()

waktu2 = datetime.now()
print(f"\nNLPD Finish : {waktu2}")
print(f"Waktu Proses : {waktu2 - waktu1}")
print(f"Semua data berhasil dilabeli dan disimpan di: {output_csv}")