In [ ]:
import pandas as pd
import warnings
import cudf
import cupy as cp
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

## 5 Cross Validation Sampling

In [ ]:
data_prep = pd.read_csv("data_hasil_preprocessing.csv")
data_prep.head()

,review_detail,case_folded,tokenized,no_stopwords,lemmatized,clean_review
0,"I enjoyed the first season, but I must say I t...",i enjoyed the first season but i must say i th...,"['i', 'enjoyed', 'the', 'first', 'season', 'bu...","['enjoyed', 'first', 'season', 'must', 'say', ...","['enjoyed', 'first', 'season', 'must', 'say', ...",enjoyed first season must say think season eve...
1,I know Iceland is a small country and police d...,i know iceland is a small country and police d...,"['i', 'know', 'iceland', 'is', 'a', 'small', '...","['know', 'iceland', 'small', 'country', 'polic...","['know', 'iceland', 'small', 'country', 'polic...",know iceland small country police thing bit di...
2,"Except K K , no other actor looks comfortable ...",except k k no other actor looks comfortable in...,"['except', 'k', 'k', 'no', 'other', 'actor', '...","['except', 'k', 'k', 'actor', 'looks', 'comfor...","['except', 'k', 'k', 'actor', 'look', 'comfort...",except k k actor look comfortable acting fight...
3,I'm guessing that as a 62 year old white woman...,im guessing that as a year old white woman im ...,"['im', 'guessing', 'that', 'as', 'a', 'year', ...","['im', 'guessing', 'year', 'old', 'white', 'wo...","['im', 'guessing', 'year', 'old', 'white', 'wo...",im guessing year old white woman im target dem...
4,Here's the truth. There's not much to this mov...,heres the truth theres not much to this movie ...,"['heres', 'the', 'truth', 'theres', 'not', 'mu...","['heres', 'truth', 'theres', 'much', 'movie', ...","['here', 'truth', 'there', 'much', 'movie', 's...",here truth there much movie sucked high rating...

In [3]:
data_sampling = pd.read_csv("data_sampling_labelbagging.csv")
data_sampling.head()

,review_id,movie,rating,review_detail,label_komen
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t...",1
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...,0
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ...",0
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...,1
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...,0

In [4]:
data_sampling["clean_review"] = data_prep["clean_review"]
data_sampling.head()

,review_id,movie,rating,review_detail,label_komen,clean_review
0,rw5704482,After Life (2019– ),9.0,"I enjoyed the first season, but I must say I t...",1,enjoyed first season must say think season eve...
1,rw5704483,The Valhalla Murders (2019– ),6.0,I know Iceland is a small country and police d...,0,know iceland small country police thing bit di...
2,rw5704484,Special OPS (2020– ),7.0,"Except K K , no other actor looks comfortable ...",0,except k k actor look comfortable acting fight...
3,rw5704485,#BlackAF (2020– ),8.0,I'm guessing that as a 62 year old white woman...,1,im guessing year old white woman im target dem...
4,rw5704487,The Droving (2020),2.0,Here's the truth. There's not much to this mov...,0,here truth there much movie sucked high rating...

### Imbalance per Batch

In [5]:
d_data = data_sampling.to_dict(orient="list")

In [6]:
data_5_val = [{"clean_review" : [] , "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []}]

counter = 0

for j in data_5_val :
    for k in range(data_sampling.shape[0] // 5) :
        j["clean_review"].append(d_data["clean_review"][counter])
        j["label_komen"].append(d_data["label_komen"][counter])
        counter+=1
else :
    for k in range(data_sampling.shape[0] % 5) :
        data_5_val[k]["clean_review"].append(d_data["clean_review"][counter])
        data_5_val[k]["label_komen"].append(d_data["label_komen"][counter])
        counter+=1
        
data_5_val

[{'clean_review': ['enjoyed first season must say think season even stronger ricky great job writer actor director brings best superb supporting cast one thing id change id like hear talk less people speak third person pretty hard fault funny yet emotional comedy',
   'know iceland small country police thing bit different europe cmon incompetent police work robs show believability st detective hey got two person interest need talk one could possibly serial killer one visit first nd detective let split',
   'except k k actor look comfortable acting fight scene funny plot repeattative',
   'im guessing year old white woman im target demographic enjoyed show good see others perspective loved wry humor entertaining office park rec make broad negative assumption white though',
   'here truth there much movie sucked high rating overly positive review must submitted cast film crew wont give technical analysis like ameteur movie critic sincere opinionthe droving annoying jump due able hear opening dialogue ambient sound time difficult hear said turn caption knew droving starting negative balance really good thing happen moving forward win overfilm beautiful many nature scene appear low budget standpoint also decent pace didnt fall asleep close occasion thing stated cinematographer pace could save film rightfully sowhere droving fall apart story humble opinion premise interesting story well developed main character almost much mystery movie story climax anticlimactic evolves rapidly abrupt ending left scratching headfinally worse movie droving potential good watch missed mark majorly story character development background sound made difficult time hear dialogue ending total letdown making film bypassed movie option',
   'seen film first time today year release still impact outstanding excellent writing directing performance around particularly bette davis anne baxter respective immortal role well unpredictable filled complex character relationship eve one best movie ever seenas got halfway movie thought jealousy resentment drive people away movie manipulation horrible people con people getting want great film',
   'movie impressive scene especially one involved cast fumbling around rail car incident train plus runaway train crashing thing pretty coolas watching thinking bad acting two lead jon voight especially voice comical find nominated academy award didnt get itworth watch guess',
   'loved first episode couldnt stop bingewatching love plot actor connection show action scene share punchbloodbloodandmorebloodkickass spirit',
   'see netflix teenagekids audience making yet another typical romcom movie suppose stand rest netflix standardsunfortunatelythe writing horrible love messy doesnt mean writing messy seemed like writer wanted make messy love story forgot actually focus story rather used quote left u nothing character depth felt like writer trying hard make sound philosophical rather normal teenager trying actually find love year old mind needed another h min cover many messy part moviewhat triggeres whole movie main core love movie follows love messy actully never focus long journey sudden movie rushed ending protagonist find key love know everything love kiss cliche quote comeon show u livelihood love vague idea written book random quote universe starsof course soundtrack good occopy teenager mind think movie great even though star acting soundtrack editing etc',
   'show people nothing even mildly bad ever happened wallow mediocre misery others keep mind pearsons incredibly high maintenance self righteous there pearsons there everyone else petty concern',
   'fun intriguing mystery acting strong catia ojeda great job lead funny film lot quirky character also look great bonus dee wallace',
   'suspenseful thrilling adventure loose train worker inside denzel washington chris pine try stop sound incredible nice least nominated oscar cinematography wildly beautiful unstoppable great ride glorious film',
   'lot excuse apologizing politically incorrect work past wish owned thought funny shouldnt apologize comedy',
   'fenomel animation fabulous storyline vivid example imagination',
   'kind hate lincoln ronen rubenstein goth bullied home school finally strike back stabbing bully face fork end sent mind eye academy reform school desert encourages spiritual growth face bully angst summons vengeful ghost moira sierra mccormick girl committed suicide school due bullying begin deal bully blood run freely moira make look bully committing suicide terrifying behold limb slashed selfharming wearing necklace razor blade disturbing film stick mind long final credit roll good performance rubenstein mccormick imdb think director adam egypt mortimer bloody horror flick deserves horror channel',
   'actually liked movie traumatized little brother yr old used watching horror movie together movie scared point fainted definetely dont watch little kid sibling',
   'well finished watching gaspar no carne seen movie many people know carne minute short film feature length film debut feature film stand alone actually direct continuation occurs carne though known stand alone since didnt hear carne year actually think carne superior stand alone short runtime paced quickly feature gaspar stylish cutting editing thoroughly entertaining stand alone slowburning ickyfeeling build wretched climax make pretty much everyone feel like need take shower afterwardsany way movie good probably one best short film ever seen singular style turned performance point dialogue subject matter visuals immensely jarring though stand alone movie would ever recommend anyone sickening subject matter suggest interested watch stand alone without seeing carne first watched sequence one watch something like kill bill vol ive seen gaspar no film would rank orderenter void irreversible climax carne love stand alone',
   'ah indie done brainerds rever verbose french new wave intellectual misfit loss communicate others especially sex bad offered type character acting decoy screenwriter psychoanalysis thus get boring train selflamentation moaning perennial inability pull oneself one bootstrapsbring good cast fine production value opposed erratic camera work postmodernist setting spread cutting back forth timeline bam get cutesy indie usual might excellent short provided main character beefed self deprecating humor instance',
   'everybody watch movie pure art difficult even explain genre includes realism surrealism drama comedy critique society psychological matter every dialogue scene meaningful never came pretentious quite opposite memory mastroianni best satisfying scene history cinema actually think whole asa nisi masa scene best scene ever made real work art many time watch old movie get feeling depicting something belongs past past way depict thing linear movie truly universal one important piece history cinema',
   'james fitzpatrick sends technicolor camera nova scotia supervision cinematographer virgil miller war mgm traveltalks series could venture far afield meant distant canada spends much time babbling usually information gathered almanac governmental brochure know nova scotia sent million half barrel apple every year britain large barrel find let knowmost image fairly rustic including covered bridge pleasant countryside copy play turner classic movie good shape image pleasant fitzpatrick would shut let u enjoy',
   'premise execution left good bit desired certain area',
   'dont usually write review make imdb account write review one great work director anubhav sinha masterpiece part social discussion people barely speak must watch men might awakening u men needed one movie bring change thought process behaviour lot men also glimpse realisation men thought okay woman take beating theni would also like add men like movie men think superior woman movie hurt ego',
   'love two main character mystery delightful cute',
   'low budget though good cast many story hole disapointing ambitous tried give u parasite ending failed terribly',
   'already loved andy samberg lonely island several film starred found brooklyn ninenine show taken ability make cry laughter another level worthy credit must humongously mentioned well dan goor michael schur writing masterpiece show tv goldhaving arrived late show started watching season came knew opportunity binge watch season upon season liked took episode know show big fan pilot second episode season better third wanted watch one best part rewatch old episode feel like watching first time againthe character fit together way without anyone overplaying part theyre also hilariously funny practically extremely likeable none imo gina linetti chelsea peretti also additionally could possibly say amy santiago jake peralta quite argubaly best couple come tv show potentially ever furthermore also love terry fascination yoghurt speaking third person rosa character development throughout show captain holt unique take lifeall favourite show hope commissioned series finished current one',
   'love everything show thought couldnt improve series think cried every episode character well drawn human ricky phenomenal comedian brilliant actor portrayal grief stricken husband break heart genuinely feel pain despite odd glimmer happy man used course mention dog oh god love dog watch show please prepare tear keep great work ricky youre legend',
   'one worst movie ever seen terrible plot even worse acting whole movie shockingly bad watch save time',
   'umm say doesnt give away spoiler every keep toe element seemed unnecessary still huge cliffhanger knew watch dont enjoy gon na take away goodnight sleep still good watch hate eklavya thinking purely based woman human',
   'girlfriend started watching hooked sadly finding season hope continue making season loved drama latino pride also lgbt community love dont sugar code anything',
   'guess world gotten serious movie like',
   'woo family make family look normal thats scary first episode tedious told horrible danny without much reason finally start showing true color way felt organic many lie unspoken truth many family secret interest held several episode end end couldnt figure people want others life miserable relationship toxic good show worthy watching hard get behind character want one make good choice keep chasing bad choice bad choice',
   'load toshabsolute waste time real story cardboard acting like watching violent series heartbeat',
   'kid saw classic educational family sitcom like way parent child communicate like friend liu xing eldest son three child really mischievous also give audience lot joy like xiadonghai educate child rationally time im older feel relaxed watch play good play relieve pressure',
   'show incredible every bit satisfying kept waiting something go horribly wrong time period way would allowed happen back show set may fantasy imagining world could happened year ago incredibly wonderful thought',
   'simple relatable right amount humour ricky gervais made laugh cry time brilliant wish story like',
   'unrealistic mean way living complex',
   'overall worthy binge watching series prince character youd find realistic youll know hit season odd thing seobi avoid zombie single fireball soldier died end even know zombie afraid fire doesnt make sense',
   'animation detail quality mostly blue one animated average best time average blocky cheap script cheap formula nasty human villain steal power blue one course another human rescue villain highlight mustache flat humorless dialogue aimed probably middle school level really bad science fill people brain besides faster light biological forget energy demand really dumb ring portal opposite side universe obviously writer idea really mean sound good left open easy money junk food wour nasty scheming way back',
   'good story watch lot hallmark movie pulled heartstrings',
   'amazing series funny heartwarming cant wait nd season',
   'jennie rooneys novel red joan based true story british physicist melita norwood unmasked kgb longest serving british spy age transferred screen lindsay shapero direction trevor nunn story becomes time lapse chronicle young joan acting conviction elderly joan facing trial actsvery briefly joan stanley judi dench elder joan sophie cookson young joan physicist becomes employed british government civil servant work professor max davy stephen campbell moore together work concept physic deal creating atomic bomb courted friend sonja tereza srbova brother leo tom hughes supporter soviet party convinced share information making bomb stalin russia partly joan hypothetically belief powerful country access bomb order maintain equality prevent abuse bomb manner u used destruction hiroshima nagasaki mixed love affair fear joan transfer secret information soviet russia secrecy last mi agent arrest film open contemporary time flash back forth manner make story crediblean excellent cast especially dench cookson brings story life impact whether agree premise make film absorbing g',
   'effect dazzling physic much scene father friend trying navigate around huge space station airlock ignition jupiter felt like science died two teenager group policeman going revive overly melodramatic people dont cry every single occasion comic relief bad take better conversation film still though special effect second none grandfather best actor',
   'show like christian show depicts disciple christ character unique personality feel like real people relate reach character even jesus human personality interaction jesus everyone brings tear eye personal brings many emotion wish episode never ended',
   'oh god world name movie pathetic piece overindulgence called cinema making start called direction sorry dont expect cause whoever directed worthy directing even second youtube video next stop acting let tell one thing besides manoj bajpai way ham part jacqueline wont even recognize rest pathetic display actor cast themwhy wrote netflix even produce garbage please trust review way opposite camp tarnish utter garbage avoid dont even watch trailer hopeless',
   'hethey dont even get another dog make sense none enzo taken everywhere there way get new dog would race track adopt dont shop otherwise interesting thing learned quaint film one better thing watch tv day may',
   'binged two day hilarious time terrific drama well lead actor excellent chemistry make even pleasure watch definitely altered carbon vibe san junipero episode black mirror',
   'apparently writer director thought big name actor plus lot gi joes screaming yelling loudest little kid squealing non stop would good substitute somethinganything might look like alien invading earth didnt p poor movie prof hope never accidentally watch loud bunch time wasted film bon appetitsummary knew outer space alien wanted live los angeles must read liberal news article many illegal alien living democrat welcome show vote one party political mailinyour vote vote vote system',
   'old hat blonde people evil people good nice violence',
   'predictible sweet little movie pace christian movie',
   'enjoyed sonic hedgehog movie well time couldnt stop thinking actor act absolutely nothing look right little blue creature running around course whole story changed little blue creature think definitely changed better real thing couldnt stop thinking watched sonic movie better movie career sonic going mario surprise beautiful way sonic sega enact final albeit small revenge nintendo loss console war sonic movie definitely better mario movie although year ago better mario tv show toojim carrey fantastic dr robotnik expect even better sequel sonic actually likable cartoon character rest human cast fine job supporting similar garfield movie really enjoyed sonic movie id suggest watching thanks much reading review hope liked',
   'good place start review bad movie like bad cross superman oman kid come space crash land farm parent know thisstrange thing start happen involving parent dont seem think big deal movie lost son space think he capable unusual conductseems like college kid got drunk wrote idea movie parent good movie producer gave nonsense green light make im tired bad movie total rip offs silly cliche twist',
   'show good adventure treasure hunt vibe love mystery reminds blood treasure treasure hunt show movie dialogue well written every character unique vocabularythe big thing shocked character said youre episode say time theyre sixteenyearolds teenager mind character maybe especially seeing using drug drinking happen course felt bit unreal topin completion first season fun watch much potential second one curious take show especially read writer planning season show',
   'movie packed great action effect main character well developed grow secondary character much fun ride im giving rating based movie wanted people may expected deep sci fi depth delving whole situation group marine trying survive odds showing extreme heroism like kind thing youll like movie',
   'international anthology local folklore story short good twist interesting topic included haunted palace kallikantzaro trud djinn virgin tale melonheads princess curse course qunicy jones drudeguide fword nudity marlene hauser luzia oppermann urszula zerek',
   'loved every minute binge watched episode one go funny silly action packed easy watch full british humour wit actor make storyline enjoyable dont overthink open bottle vine sit back laugh thank much absolutely love stephen graham reason picked series proved one best british actor seen richard gadd funny work well together please make another series asap',
   'fun lighthearted romantic comedy five story young love easily relatable millennial crowd glimpse back sweet awkward day dating older crowd cute movie',
   'complex complicated whole film consists flashback hard watch youre solving puzzle end still piece puzzle lacking complex story many flashback red thread',
   'watched mistake thinking invisible man thought id see end writing review others done waste tad hour life wont discus negative wouldnt know start',
   'series novel concept someone dying want life life fullest ambitious cop manipulates situation story acting direction notch acting good lead also supporting cast rinku prof lara outdid best part music experience best use retro music brings back life iconic song others pretty much forgotten good watch extra star music',
   'youre avid watcher series already know great isthere change coming telegraphed last season leave door open future giamatti usual self draw everyone back great character interesting multi leveled series tight everyone involved hit mark refreshing hear interesting dialog watch twisting subterfuge played well',
   'loved series first dvd set watch exercising made good humanity mannix script intelligent joe likable always wanting right thing chuckle though seemed use basement set throughout series would change item scene joe got driven road several episode notice watch episode sometimes day week bottom line series withstood time great care went plot filming terrific real pro behind camera mike connors gentleman even show going matt helmin movie series dean martin wanted role worked',
   'enjoyed series kept caring happened next even though plot contrived depth social issue raised without resolution cultural artifact write dialogue around consequence every action implied yet karma randomthe theme family parenthood existence messy enterprise line character disconnected also highlight america way self absorbed emotion structured around past dictate peer medium dogmatically controlled defense mechanism defy change growth',
   'barnaby acting like schoolgirl reliving music crush okay episode maybe many obnoxious character one glaring error barnaby noting eagle made big desperadothey big desperado',

In [7]:
summ = 0
for i in data_5_val :
    summ += len(i["clean_review"])
summ

295357

In [ ]:
for i in range(len(data_5_val)) :
    data_5_val[i] = cudf.DataFrame(data_5_val[i])

### Balance per Batch

In [9]:
data01terpisah = {"pos" : {"clean_review" : [], "label_komen" : []}, "neg" : {"clean_review" : [], "label_komen" : []}}
summm = {"pos" : 0, "neg" : 0}
for i in range(data_sampling.shape[0]) :
    if d_data["label_komen"][i] == 0 :
        data01terpisah["neg"]["clean_review"].append(d_data["clean_review"][i])
        data01terpisah["neg"]["label_komen"].append(d_data["label_komen"][i])
        summm["neg"] += 1
    else :
        data01terpisah["pos"]["clean_review"].append(d_data["clean_review"][i])
        data01terpisah["pos"]["label_komen"].append(d_data["label_komen"][i])
        summm["pos"] += 1
        
print(summm)

{'pos': 172766, 'neg': 122591}

In [10]:
data_5_val2 = [{"clean_review" : [] , "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []},{"clean_review" : [], "label_komen" : []}]

counter = 0
for j in data_5_val2 :
    for k in range(summm["pos"] // 5) :
        j["clean_review"].append(data01terpisah["pos"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["pos"]["label_komen"][counter])
        counter+=1
else :
    for k in range(summm["pos"] % 5) :
        j["clean_review"].append(data01terpisah["pos"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["pos"]["label_komen"][counter])
        counter+=1
        
counter = 0
for j in data_5_val2 :
    for k in range(summm["neg"] // 5) :
        j["clean_review"].append(data01terpisah["neg"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["neg"]["label_komen"][counter])
        counter+=1
else :
    for k in range(summm["neg"] % 5) :
        j["clean_review"].append(data01terpisah["neg"]["clean_review"][counter])
        j["label_komen"].append(data01terpisah["neg"]["label_komen"][counter])
        counter+=1

In [11]:
summ = 0
for i in data_5_val2 :
    summ += len(i["clean_review"])
summ

295357

In [ ]:
for i in range(len(data_5_val2)) :
    data_5_val2[i] = cudf.DataFrame(data_5_val2[i])

## LETSGOOO GRID SEARCHHHH!!!!

In [19]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN, SMOTETomek

from cuml.naive_bayes import MultinomialNB
from cuml.linear_model import LogisticRegression
from cuml.svm import LinearSVC
from cuml.ensemble import RandomForestClassifier

model_nb_tuned = MultinomialNB(
    alpha=0.1          # Smoothing parameter: Membantu mengatasi masalah kata yang tidak ada di data training.
                       # Catatan: cuML MultinomialNB belum mendukung parameter fit_prior seperti scikit-learn.
)

model_lr_tuned = LogisticRegression(
    C=2.0,              # Regularisasi: Nilai lebih kecil = regularisasi kuat (mencegah overfitting). 
                        # Nilai lebih besar = model lebih fitting ke data training.
    solver='qn',        # Algoritma optimasi: 'qn' (Quasi-Newton/L-BFGS) adalah default di cuML yang sangat cepat 
                        # memanfaatkan GPU. cuML belum menyediakan solver 'saga'.
    max_iter=1000,      # Jumlah iterasi maksimum: Batas iterasi optimasi. Naikkan jika model belum konvergen.
    linesearch_max_iter=50 # Parameter khusus cuML: Batas iterasi pencarian jalur optimasi untuk menstabilkan solver 'qn'.
)

model_svm_tuned = LinearSVC(
    C=1.0,              # Penalti regularisasi: Mengontrol keseimbangan antara margin yang lebar dan meminimalkan kesalahan klasifikasi.
    loss='squared_hinge', # Fungsi loss: Fungsi penalti standar untuk LinearSVC.
    max_iter=2000,      # Batas iterasi: Ditargetkan agar kalkulasi pada data besar selesai dengan sempurna di GPU.
    fit_intercept=True  # Menentukan apakah bias/intercept perlu dihitung (secara default True di scikit-learn).
                        # Catatan: cuML LinearSVC tidak memerlukan parameter random_state karena sifat optimisasinya di GPU.
)

model_rf_tuned = RandomForestClassifier(
    n_estimators=200,      # Jumlah pohon keputusan: Lebih banyak pohon = lebih stabil dan akurat. Di GPU prosesnya akan tetap instan.
    max_depth=20,          # Kedalaman maksimum pohon: Membatasi kompleksitas pohon agar tidak overfitting dan hemat memori GPU.
    min_samples_split=5,   # Sampel minimum untuk split: Jumlah sampel minimal di sebuah node sebelum dipecah menjadi cabang baru.
    n_bins=15,             # Parameter khusus cuML: Jumlah bin diskritisasi untuk fitur kontinu. cuML menggunakan ini 
                           # untuk mempercepat kalkulasi split di GPU secara signifikan.
    random_state=42        # Konsistensi hasil: Memastikan pembuatan pohon menghasilkan hasil yang sama setiap kali dijalankan.
                           # Catatan: Parameter n_jobs=-1 dihapus karena cuML secara otomatis menggunakan seluruh core paralel GPU.
)

In [ ]:
from cuml.feature_extraction.text import TfidfVectorizer
import heapq as hq
from cuml.metrics import accuracy_score

data_5_batch = {"Imbalance" : data_5_val, "Balance" : data_5_val2}

list_imbalancer = {
    "Tanpa Imbalancer" : None,
    "Smote" : SMOTE(random_state=42),
    "Random Under Sampler" : RandomUnderSampler(random_state=42),
    "Smote Enn" : SMOTEENN(random_state=42),
    "Smote Tomek" : SMOTETomek(random_state=42)
}

tuning_nb = {"alpha" : [0.01, 0.1, 0.5, 1.0, 5.0, 10.0]}
tuning_svm = {"C": [], "loss" : [], "max_iter" : [], "fit_intercept" : []}
tuning_rf = {"n_estimators" : [], "max_depth" : [], "min_samples_split" : [], "n_bins" : []}
tuning_lr = {"C" : [], "solver" : [], "max_iter" : [], "linesearch_max_iter" : []}

qiu_primer = []
counter = 0
for h in data_5_batch:
    paket_data = data_5_batch[h]
    
    for i in range(len(paket_data)):
        train = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
        test = cudf.DataFrame({"clean_review" : [], "label_komen" : []})
        batch_data_test = i
        
        for j in range(len(paket_data)):
            if j == i:
                test = cudf.concat([test, paket_data[j]], axis=0, ignore_index=True)
            else:
                train = cudf.concat([train, paket_data[j]], axis=0, ignore_index=True)
        
        train['clean_review'] = train['clean_review'].fillna('')
        test['clean_review'] = test['clean_review'].fillna('')
        
        tfidf_vectorizer = TfidfVectorizer(
            min_df=5,
            max_df=0.8,
            max_features=10000
        )
        
        x_train = tfidf_vectorizer.fit_transform(train['clean_review'])
        x_test = tfidf_vectorizer.transform(test["clean_review"])
        
        y_train = train["label_komen"]
        y_test = test["label_komen"]
        
        for j in list_imbalancer:
            imbalancer_name = j
            
            if j != "Tanpa Imbalancer":
                x_train_dense = x_train.toarray()
                y_train_cpu = y_train.to_pandas() 

                x_train, y_train = list_imbalancer[j].fit_resample(x_train_dense, y_train_cpu)
                x_train = cp.array(x_train)
                y_train = cudf.Series(y_train)
            
            qiu_sekunder = []
            for k in tuning_nb["alpha"] :
                model = MultinomialNB(alpha= k)
                model.fit(x_train, y_train)
                y_pred = model.predict(x_test)
                akurasi = accuracy_score(y_test, y_pred)
                hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"MultinomialNB(alpha = {k})"))
                counter += 1
            hasil = hq.heappop(qiu_sekunder)
            model_nb = (-hasil[0],hasil[2],hasil[3])
            y_pred_train_nb = hasil[2].predict(x_train)
            y_pred_test_nb = hasil[2].predict(x_test)
            
            qiu_sekunder = []
            for k in tuning_svm["C"] :
                for l in tuning_svm["loss"] :
                    for m in tuning_svm["max_iter"] :
                        for n in tuning_svm["fit_intercept"] :
                            model = LinearSVC(C = k, loss = l, max_iter = m, fit_intercept = n)
                            model.fit(x_train, y_train)
                            y_pred = model.predict(x_test)
                            akurasi = accuracy_score(y_test, y_pred)
                            hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"LinearSVC(C = {k}, loss = {l}, max_iter = {m}, fit_intercept = {n})"))
                            counter += 1
            hasil = hq.heappop(qiu_sekunder)
            model_svc = (-hasil[0],hasil[2],hasil[3])
            y_pred_train_svc = hasil[2].predict(x_train)
            y_pred_test_svc = hasil[2].predict(x_test)
            
            qiu_sekunder = []
            for k in tuning_rf["n_estimators"] :
                for l in tuning_rf["max_depth"] :
                    for m in tuning_rf["min_samples_split"] :
                        for n in tuning_rf["n_bins"] :
                            model = RandomForestClassifier(n_estimators = k, max_depth = l, min_samples_split = m, n_bins = n)
                            model.fit(x_train, y_train)
                            y_pred = model.predict(x_test)
                            akurasi = accuracy_score(y_test, y_pred)
                            hq.heappush(qiu_sekunder,(-akurasi,counter,model,f"RandomForestClassifier(n_estimators = {k}, max_depth = {l}, min_samples_split = {m}, n_bins = {n})"))
                            counter += 1
            hasil = hq.heappop(qiu_sekunder)
            model_rf = (-hasil[0],hasil[2],hasil[3])
            y_pred_train_rf = hasil[2].predict(x_train)
            y_pred_test_rf = hasil[2].predict(x_test)

5 Cross Validation Sampling V

pecah jadi Train dan Test V

tf idf

imbalancer

training base model

training meta model